nodes:
- input.visual:
    source: img.png
    threading: True
    buffering: True

- model.csrnet
- dabble.fps                        
- draw.legend: 
    show: ["count", "fps"]    
- output.screen:
    window_size: {width: 1920, height: 1080}
- output.media_writer:
    output_dir: "processed-footage/videos"
- output.csv_writer:
    stats_to_track: ["count"]
    file_path: "processed-footage/logs/footage.csv"
    logging_interval: 0



